name: build

env:
  VMLINUX_KERNEL: linux-6.0
  VMLINUX_BUSYBOX: busybox-1.34.1

on:
  push:
    branches:
      # build on all branches except master
      - '*'
      - '!master'
    tags:
      # build on release tags only
      - 'r[0-9]+*'
      - 'v[0-9]+*'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install prerequisites
        run: |
          sudo apt install build-essential libncurses-dev libssl-dev libelf-dev bison flex bc
      - name: Download Linux kernel source
        run: |
          wget -q https://cdn.kernel.org/pub/linux/kernel/v6.x/$VMLINUX_KERNEL.tar.xz
          tar xf $VMLINUX_KERNEL.tar.xz
      - name: Download Busybox source
        run: |
          wget -q https://busybox.net/downloads/$VMLINUX_BUSYBOX.tar.bz2
          tar xf $VMLINUX_BUSYBOX.tar.bz2
      - name: Prepare environment
        id: environment
        run: |
          # see https://reproducible-builds.org/specs/source-date-epoch/
          SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          echo SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH >>$GITHUB_ENV
          echo release_name=$(date --date=@$SOURCE_DATE_EPOCH +%Y-%m-%d) >>$GITHUB_ENV
          # VMLINUX_RELEASE
          VMLINUX_RELEASE="r$(date --date=@$SOURCE_DATE_EPOCH +%y%m%d)"
          echo VMLINUX_RELEASE=$VMLINUX_RELEASE
          echo VMLINUX_RELEASE=$VMLINUX_RELEASE >>$GITHUB_ENV
      - name: Build Busybox
        run: |
          cd $VMLINUX_BUSYBOX
          cp ../busybox.config .config
          make oldconfig
          make -j4
      - name: Build Linux kernel
        run: |
          cd $VMLINUX_KERNEL
          mkdir initramfs
          cp ../$VMLINUX_BUSYBOX/busybox initramfs
          touch initramfs/init.sh
          echo '#!/bin/busybox sh'                              >> initramfs/init.sh
          echo /bin/busybox --install                           >> initramfs/init.sh
          echo exec /bin/sh                                     >> initramfs/init.sh
          touch initramfs/source
          echo file /init initramfs/init.sh 755 0 0             >> initramfs/source
          echo dir /bin 755 0 0                                 >> initramfs/source
          echo dir /sbin 755 0 0                                >> initramfs/source
          echo file /bin/busybox initramfs/busybox 755 0 0      >> initramfs/source
          cp ../vmlinux.config .config
          make oldconfig
          make CONFIG_INITRAMFS_SOURCE=initramfs/source -j4
      - name: Package vmlinux
        run: |
          cd $VMLINUX_KERNEL
          zip -9 ../vmlinux-$VMLINUX_KERNEL-$VMLINUX_RELEASE.zip vmlinux
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vmlinux
          path: |
            vmlinux-*.zip
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: vmlinux ${{ env.release_name }}
          body: |
            Included:
            - ${{ env.VMLINUX_KERNEL }}
            - ${{ env.VMLINUX_BUSYBOX }}
          files: vmlinux-*.zip
